defaults: &defaults
  
  EMAIL_NOTIFICATION:
      - ranieripieper@gmail.com
      
  CODE_SHOPPING_MORUMBI: 1
  CODE_SHOPPING_MARKETPLACE_SP: 2
  CODE_SHOPPING_IGUATEMI_SP: 3
  CODE_SHOPPING_IGUATEMI_ALPHAVILLE: 4
  CODE_SHOPPING_IGUATEMI_CAMPINAS: 5
  CODE_SHOPPING_IGUATEMI_FLORIANOPOLIS: 6
  CODE_SHOPPING_IGUATEMI_BRASILIA: 7
  CODE_SHOPPING_IGUATEMI_SAO_CARLOS: 8
  CODE_SHOPPING_IGUATEMI_BOULEVARD_RIO: 9
  CODE_SHOPPING_IGUATEMI_PRAIA_BELAS: 10
  CODE_SHOPPING_IGUATEMI_GALLERIA: 11
  
  CODE_CATEG_OUTROS: 1
  
   
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults