defaults: &defaults
    categories:
      #CATEGORIA_SHOPPING : CODE_CATEGORIA_SHOPFINDER
        "7-147": 42
        "7-33": 2
        "4-58": 3
        "5-27": 4
        "7-78": 5
        "7-35": 6
        "6-12": 7
        "6-13": 8
        "6-14": 9
        "6-15": 5
        "7-36": 10
        "6-16": 11
        "7-37": 12
        "4-59": 13
        "4-60": 13
        "4-61": 13
        "4-62": 13
        "4-63": 13
        "5-28": 14
        "7-38": 15
        "6-17": 16
        "1-52": 17
        "7-39": 41
        "7-40": 18
        "1-53": 19
        "5-29": 20
        "7-77": 21
        "7-43": 22
        "7-150": 23
        "7-44": 27
        "6-86": 24
        "6-18": 25
        "6-19": 26
        "7-46": 28
        "4-84": 29
        "6-20": 30
        "2-57": 31
        "5-30": 32
        "4-64": 29
        "4-65": 43
        "4-66": 33
        "6-21": 26
        "6-22": 1
        "5-32": 34
        "1-54": 19
        "7-47": 41
        "4-67": 40
        "6-23": 35
        "6-24": 42
        "7-89": 36
        "6-25": 37
        "7-50": 38
        "6-26": 39
        "4-68": 40
        "4-69": 40
        "4-70": 40
        "4-71": 40
        "4-72": 40
        "4-116": 40

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults